name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep '@smoke'
    
    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev || true

    - name: Generate Allure Report (HTML)
      run: allure generate allure-results --clean -o allure-report

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Convert Allure HTML report to PDF
      run: |
        wkhtmltopdf --enable-local-file-access allure-report/index.html allure-report.pdf

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        allurename: allure-report-pdf
        allurepath: allure-report.pdf
        retention-days: 30
